const fs=require('fs'),vm=require('vm'),assert=require('assert'),os=require('os'),path=require('path'),{execFileSync}=require('child_process');
const {createCanvas,Path2D,DOMMatrix,loadImage}=require('@napi-rs/canvas');
const root=require('path').resolve(__dirname,'..');
const html=fs.readFileSync(root+'/index.html','utf8');
const els={},stored=new Map(),pending=[];
function element(id='',value='') {return {id,value,checked:false,disabled:false,textContent:'',style:{setProperty(){}},dataset:{},attributes:{},handlers:{},options:[],addEventListener(t,f){(this.handlers[t]??=[]).push(f)},setAttribute(k,v){this.attributes[k]=v},removeAttribute(k){delete this.attributes[k]},append(){},click(){for(const f of this.handlers.click||[])f()},remove(){},pause(){},load(){},showModal(){this.open=true},close(){this.open=false;(this.handlers.close||[]).forEach(f=>f())}};}
for(const tag of html.matchAll(/<(input|select|button|canvas|div|p|strong|dialog|img|video|progress|span|a)\b[^>]*\bid="([^"]+)"[^>]*>/g)){const e=els[tag[2]]=element(tag[2],/\bvalue="([^"]*)"/.exec(tag[0])?.[1]||'');e.checked=/\bchecked\b/.test(tag[0]);}
els.preset.options=['1290x2796','1206x2622','1179x2556','1170x2532','custom'].map(value=>({value}));
const c=createCanvas(1290,2796);c.setAttribute=()=>{};c.toBlob=(cb,mime,q)=>c.encode(mime==='image/jpeg'?'jpeg':'png',Math.round(q*100)).then(b=>cb(new Blob([b],{type:mime})));
els.canvas=c;const preview=createCanvas(620,1344);preview.setAttribute=()=>{};preview.getBoundingClientRect=()=>({width:310});els.previewCanvas=preview;
const outputs=[...html.matchAll(/<output[^>]*for="([^"]+)"/g)].map(m=>({htmlFor:m[1],textContent:''}));
const context={console,window:{devicePixelRatio:1},document:{addEventListener(){},getElementById:id=>els[id],querySelectorAll:q=>q.startsWith('output')?outputs:[],createElement:t=>t==='canvas'?createCanvas(1,1):element(),body:{append(){}}},Path2D,DOMMatrix,localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v),removeItem:k=>stored.delete(k)},navigator:{userAgent:'test desktop',platform:'Linux',maxTouchPoints:0},setTimeout,clearTimeout,requestAnimationFrame:f=>{pending.push(f);return pending.length},cancelAnimationFrame(){},Blob,File,URL};
vm.createContext(context);
let source=fs.readFileSync(root+'/app.js','utf8');source=source.replace('updateUI(true);render();\n})();','updateUI(true);render();\nthis.qa={get state(){return state},set(raw){state=sanitize({...state,...raw});updateUI(true);changed();render()},render,makeBlob,filename,hslToHex,drawText,motionProgress,liveMotionProgress,videoDimensions,partialHello,movieMeta,movieLoopData,movWithContentIdentifier,LIVE_DURATION,get prepared(){return prepared}};\n})();');
vm.runInContext(source,context);const qa=context.qa;
(async()=>{
 let count=0;function check(label,test){test();count++;console.log('PASS '+label)}
 check('Default canvas dimensions',()=>assert.equal(c.width+'x'+c.height,'1290x2796'));
 check('Default output labels',()=>assert.equal(outputs.find(o=>o.htmlFor==='dotSize').textContent,'2.2 px'));

 const base=Buffer.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data);
 for(const [key,value] of Object.entries({bg1:'#99aacc',bg2:'#bbccdd',gradient:0,vignette:40,dotSize:4,spacing:28,dotOpacity:20,dotColor:'#222222',textY:60,textX:45,textSize:70,textColor:'#333333',angle:15,stroke:140,textOpacity:40,offsetRows:true,showText:false})){const old=qa.state[key];qa.set({[key]:value});const next=Buffer.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data);check('Visible rendering change: '+key,()=>assert(!base.equals(next)));qa.set({[key]:old});}
 for(const [w,h] of [[1290,2796],[1206,2622],[1179,2556],[1170,2532],[640,960],[6000,320]]){qa.set({width:w,height:h});for(const format of ['png','jpeg']){qa.set({format});const b=await qa.makeBlob();const img=await loadImage(Buffer.from(await b.arrayBuffer()));check(`${format} ${w}x${h}`,()=>{assert.equal(img.width,w);assert.equal(img.height,h);assert.equal(b.type,format==='png'?'image/png':'image/jpeg')})}}
 qa.set({width:7000,height:12});check('Clamp 320–6000',()=>{assert.equal(c.width,6000);assert.equal(c.height,320)});
 qa.set({width:640,height:960,text:'Даниил',textColor:'#ffffff',textOpacity:100,showText:true});check('Custom text hint',()=>assert(els.textHint.textContent.includes('только для слова')));
 qa.set({format:'jpeg',quality:10});const low=await qa.makeBlob();qa.set({quality:100});const high=await qa.makeBlob();check('JPEG quality affects output',()=>assert(high.size>low.size));
 for(let i=0;i<40;i++){els.random.click();for(const key of ['bg1','bg2']){const hex=qa.state[key],v=[1,3,5].map(j=>parseInt(hex.slice(j,j+2),16)/255),max=Math.max(...v),min=Math.min(...v),l=(max+min)/2,s=(max-min)/(1-Math.abs(2*l-1));assert(l>=.67&&l<=.86);assert(s>=.32&&s<=.56)}}check('40 pastel randomizations',()=>{});
 els.reset.click();qa.render();check('Reset clears storage and restores all defaults',()=>{assert.equal(stored.size,0);assert.equal(qa.state.text,'hello');assert.equal(qa.state.width,1290);assert.equal(qa.state.bg1,'#7d74f6')});
 
 qa.set({width:640,height:960,material:'solid',text:'hello',showText:true});const plain=c.toBuffer('image/png');qa.set({material:'glass'});check('Glass differs from solid',()=>assert(!plain.equals(c.toBuffer('image/png'))));
 fs.writeFileSync(root+'/assets/glass-preview.png',c.toBuffer('image/png'));
 qa.set({glassDepth:10});const shallow=c.toBuffer('image/png');qa.set({glassDepth:100});check('Glass depth changes pixels',()=>assert(!shallow.equals(c.toBuffer('image/png'))));
 check('Animation starts empty, completes once and holds',()=>{assert.equal(qa.motionProgress(0),0);assert.equal(qa.motionProgress(.2),0);assert(qa.motionProgress(1)>0&&qa.motionProgress(1)<1);assert.equal(qa.motionProgress(2.2),1);assert.equal(qa.motionProgress(200),1)});
 const bg=createCanvas(640,960);bg.getContext('2d').fillStyle='#719ba6';bg.getContext('2d').fillRect(0,0,640,960);
 const hashes=[];for(const time of [0,.7,1.5,2.8,10]){const frame=createCanvas(640,960),ctx=frame.getContext('2d');ctx.drawImage(bg,0,0);qa.drawText(ctx,qa.state,qa.motionProgress(time),bg);hashes.push(frame.toBuffer('image/png'));}
 check('Distinct motion frames and identical held final frames',()=>{assert(!hashes[0].equals(hashes[1]));assert(!hashes[1].equals(hashes[2]));assert(!hashes[2].equals(hashes[3]));assert(hashes[3].equals(hashes[4]));});
 check('Live wallpaper motion is a single symmetric Bounce',()=>{assert.equal(qa.LIVE_DURATION,58/30);assert.equal(qa.liveMotionProgress(0),qa.liveMotionProgress(qa.LIVE_DURATION));assert.equal(qa.liveMotionProgress(qa.LIVE_DURATION/2),1);assert(Math.abs(qa.liveMotionProgress(.35)-qa.liveMotionProgress(qa.LIVE_DURATION-.35))<1e-12);});
 check('Live wallpaper MOV metadata contains Bounce variation and LOOP',()=>{const meta=Buffer.from(qa.movieMeta('TEST-ID')),loop=Buffer.from(qa.movieLoopData());assert(meta.includes(Buffer.from('com.apple.quicktime.content.identifier')));assert(meta.includes(Buffer.from('com.apple.photos.variation-identifier')));assert(meta.includes(Buffer.from([0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,2])));assert(loop.includes(Buffer.from('udta')));assert(loop.includes(Buffer.from('LOOP')));assert(loop.subarray(-4).equals(Buffer.alloc(4)));});
 const liveTmp=fs.mkdtempSync(path.join(os.tmpdir(),'hello-wallpaper-live-'));try{const sourceMp4=path.join(liveTmp,'source.mp4'),outputMov=path.join(liveTmp,'output.mov');execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=160x240:rate=30','-t',String(58/30),'-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',sourceMp4]);const liveMov=await qa.movWithContentIdentifier(new Blob([fs.readFileSync(sourceMp4)],{type:'video/mp4'}),'TEST-ID',1.9);fs.writeFileSync(outputMov,Buffer.from(await liveMov.arrayBuffer()));const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',outputMov]));check('Generated Live wallpaper MOV remains decodable',()=>{assert.equal(probe.streams[0].codec_name,'h264');assert(probe.streams.some(stream=>stream.codec_tag_string==='mebx'));assert.equal(probe.format.tags.major_brand,'qt  ');});const exif=path.resolve(root,'../.tmp-exiftool/exiftool');if(fs.existsSync(exif)){const tags=JSON.parse(execFileSync('perl',[exif,'-j','-ee','-ContentIdentifier','-StillImageTime','-ApplePhotosVariationIdentifier','-LoopStyle',outputMov]))[0];check('Generated MOV exposes all Apple wallpaper tags',()=>{assert.equal(tags.ContentIdentifier,'TEST-ID');assert.equal(tags.StillImageTime,-1);assert.equal(tags.ApplePhotosVariationIdentifier,2);assert.equal(tags.LoopStyle,'Unknown (0)');});}}finally{fs.rmSync(liveTmp,{recursive:true,force:true});}
 check('Video dimensions are even and bounded',()=>{for(const [width,height] of [[1290,2796],[6000,320],[6000,6000],[1920,1080]]){const d=qa.videoDimensions({width,height,videoSize:1080});assert.equal(d.width%2,0);assert.equal(d.height%2,0);assert(Math.max(d.width,d.height)<=2560);}});
 qa.set({material:'glass',text:'Даниил'});check('Glass supports custom text',()=>assert(c.toBuffer('image/png').length>1000));qa.set({material:'solid',text:'hello'});
 context.navigator.userAgent='iPhone';context.navigator.canShare=()=>true;let shared=0;context.navigator.share=async()=>{shared++};
 qa.set({width:640,height:960});await new Promise(r=>setTimeout(r,700));
 check('Mobile export prepared before click',()=>assert(qa.prepared));
 await els.export.handlers.click[0]();check('Prepared mobile file uses share',()=>assert.equal(shared,1));
 context.navigator.share=async()=>{const e=new Error('cancel');e.name='AbortError';throw e};await els.export.handlers.click[0]();check('Cancelled share is not an error dialog',()=>assert(!els.saveDialog.open));
 context.navigator.share=async()=>{throw new Error('unavailable')};await els.export.handlers.click[0]();check('Failed share provides image fallback',()=>assert(els.saveDialog.open&&els.savedImage.src.startsWith('blob:')));els.saveDialog.close();
 context.navigator.canShare=()=>false;await els.export.handlers.click[0]();check('No Web Share provides downloadable image',()=>assert(els.saveDialog.open&&els.share.hidden&&els.downloadImage.download==='hello-wallpaper-640x960.png'));els.saveDialog.close();
 console.log(count+' checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
